# Topics configuration for content processing

# Default settings for all topics
defaults:
  lang: [es, en]
  cadence: hourly
  cadence_minutes: 60  # Default trending analysis cadence
  max_posts_per_run: 1
  max_per_run: 5       # Maximum trending items per topic per run
  min_words: 180
  image_strategy: mixed
  credit_label: "Cortesía de"

# Topic definitions
topics:
  - key: taiwan_seguridad
    name: "Taiwán y seguridad regional"
    priority: 0.9
    cadence: hourly
    cadence_minutes: 30  # High priority topic, check more frequently
    max_per_run: 3       # Allow more trending items for important security topics
    queries:
      - '"Taiwan" OR "Taipei" OR "Taipéi"'
      - '"Taiwan Strait" OR (Estrecho NEAR/3 Taiwan)'
      - 'China AND (drills OR incursión OR ADIZ)'
    allow_domains: ["reuters.com","apnews.com","bbc.com","aljazeera.com"]
    tags: ["Asia","Defensa","China","Taiwán"]

  - name: "Empresas y Negocios"
    slug: "empresas-negocios"
    description: "Noticias corporativas, fusiones, adquisiciones y estrategia empresarial"
    cadence_minutes: 120  # Business news, check every 2 hours
    max_per_run: 4
    keywords:
      - "corporativos"
      - "CEO"
      - "fusiones"
      - "adquisiciones"
      - "earnings"
      - "resultados trimestrales"
    parent: null

  # Technology and Innovation
  - name: "Tecnología y Fintech"
    slug: "tecnologia-fintech"
    description: "Innovación tecnológica, fintech y transformación digital en México"
    cadence_minutes: 90   # Tech moves fast, check every 1.5 hours
    max_per_run: 6        # Tech generates many trending topics
    keywords:
      - "fintech"
      - "blockchain"
      - "criptomonedas"
      - "inteligencia artificial"
      - "startups tecnológicas"
      - "banca digital"
    parent: null

  # Industry Sectors
  - name: "Energía y Petróleo"
    slug: "energia-petroleo"
    description: "Sector energético, PEMEX, energías renovables y política energética"
    cadence_minutes: 180  # Energy sector, check every 3 hours
    max_per_run: 4
    keywords:
      - "PEMEX"
      - "petróleo"
      - "gas natural"
      - "energías renovables"
      - "CFE"
      - "reforma energética"
    parent: null

  - name: "Banca y Seguros"
    slug: "banca-seguros"
    description: "Sistema bancario mexicano, seguros y servicios financieros"
    cadence_minutes: 240  # Banking, check every 4 hours
    max_per_run: 3
    keywords:
      - "bancos"
      - "BBVA"
      - "Santander"
      - "Banorte"
      - "crédito"
      - "seguros"
      - "CNBV"
    parent: null

  - name: "Retail y Consumo"
    slug: "retail-consumo"
    description: "Sector retail, comercio electrónico y tendencias de consumo"
    cadence_minutes: 360  # Retail, check every 6 hours
    max_per_run: 3
    keywords:
      - "retail"
      - "e-commerce"
      - "consumo"
      - "ANTAD"
      - "centros comerciales"
      - "marcas"
    parent: null

  # Real Estate and Construction
  - name: "Inmobiliario y Construcción"
    slug: "inmobiliario-construccion"
    description: "Mercado inmobiliario, desarrollo urbano y sector constructor"
    cadence_minutes: 480  # Real estate, check every 8 hours
    max_per_run: 2
    keywords:
      - "inmobiliario"
      - "vivienda"
      - "construcción"
      - "desarrolladoras"
      - "INFONAVIT"
      - "urbanismo"
    parent: null

  # Government and Regulation
  - name: "Política Económica"
    slug: "politica-economica"
    description: "Políticas gubernamentales que impactan la economía y los negocios"
    cadence_minutes: 120  # Government policy, check every 2 hours
    max_per_run: 5        # Policy changes can be trending
    keywords:
      - "SHCP"
      - "presupuesto"
      - "regulación"
      - "comercio exterior"
      - "T-MEC"
      - "política fiscal"
    parent: null

  # International Markets
  - name: "Mercados Internacionales"
    slug: "mercados-internacionales"
    description: "Mercados globales, comercio internacional y economía mundial"
    cadence_minutes: 180  # International markets, check every 3 hours
    max_per_run: 4
    keywords:
      - "Wall Street"
      - "Fed"
      - "comercio internacional"
      - "aranceles"
      - "exportaciones"
      - "nearshoring"
    parent: null

  # Special Focus Areas
  - name: "Emprendimiento"
    slug: "emprendimiento"
    description: "Startups, emprendedores mexicanos y ecosistema de innovación"
    cadence_minutes: 360  # Entrepreneurship, check every 6 hours
    max_per_run: 3
    keywords:
      - "startups"
      - "emprendedores"
      - "venture capital"
      - "aceleradoras"
      - "ecosistema startup"
    parent: "tecnologia-fintech"

  - name: "Sostenibilidad"
    slug: "sostenibilidad"
    description: "ESG, sustentabilidad corporativa y economía verde"
    cadence_minutes: 720  # Sustainability, check every 12 hours
    max_per_run: 2
    keywords:
      - "ESG"
      - "sustentabilidad"
      - "economía circular"
      - "cambio climático"
      - "bonos verdes"
    parent: null

  - name: "Análisis y Opinión"
    slug: "analisis-opinion"
    description: "Análisis económico, opiniones de expertos y columnistas especializados"
    cadence_minutes: 480  # Analysis, check every 8 hours
    max_per_run: 2
    keywords:
      - "análisis"
      - "opinión"
      - "columna"
      - "expertos"
      - "perspectivas"
    parent: null